

=== Resumen Unidad 1
==== 17100244 - Jorge Eduardo Madrigal García

Dentro de la primera unidad se habló de:


**Modelo de Caja - (Box Model)**

 El BoxModel son propiedades que definen el espaciado
 dentro de un elemento, el cuál se encuentra dentro de
 una página web, los cuáles terminan siendo cajas rectangulares.

 Las propiedades utilizadas dentro del Box-Model son:

 * **Content-Box:** Cuando es declarada esta propiedad, el tamaño del
   contenido se puede definir con las propiedades de width,
   min-width, max-width, height, min-height y max-height.
 * **Width:** Ancho de la caja.
 * **Height:** Altura de la caja
 * **Padding:** Relleno que hay entre el contenido y el bloque.
 * **Border:** Grosor y estilo del borde que rodea el contenido(Dentro de la caja).
 * **Margin:** Espacio del borde interior y exterior del elemento.
 * **Outline:** La propiedad Outline sirve para agregar un borde extra y así
    brindar una mejor visualización del elemento.

**Propiedad Display**

 Las cajas que se generan con cada elemento dentro del html
 pueden o no mostrarse de cierta forma, es decir, podemos modificar como se
 mostrará el elemento con esta propiedad, los elementos utilizados en ella son:

 * block: Aquí mostrará el elemento dentro del flujo del documento.
 * inline: Con este elemento, se hará que las cajas estén en la misma línea con
 respecto a otros con la misma propiedad.
 * inline-box: Este elemento hará que la caja se mantenga en el flujo del
 documento y si cuenta con texto hará que lo rodeen.
 * none: Es utilizada habitualmente para esconder un elemento, sin embargo que
 este siga ocupando el espacio donde se encuentra.

**Box Sizing**

 La propiedad de box-sizing dentro de un elemento, nos dará la opción para
 incluir paddings y borders en un elemento con altura y anchura total, además de
 mostrar correctamente en el tamaño de los elementos especificados dentro de
 nuestro html.

 * **content-box: ** es la propiedad por defecto que tienen box-sizing, sin embargo los
 bordes se añadirán a el ancho final desplegado.

 * **border-box: ** con este elemento le diremos al navegador que los valores que
 se especifican se tomen en cuenta para dimensionar los objetos.

**Flujo de documento**

 El flujo es lo que indica como están colocando los componentes de la página,
 basándose en cómo aparecen en el HTML.
 Por ejemplo; la etiqueta que aparezca primero será la que se mostrará también
 en la página como primer lugar.

 sin embargo hay excepciones si se utilizan propiedades de posición, ya que con ellos
 se puede intervenir con el flujo del documento y mostrarse en una posición diferente.

**Tipos de posicionamiento**

El posicionamiento, sirve para cambiar el flujo del documento, ya que con estos se puede o
 no reservar el espacio del elemento.

 static: será estático en como se especifica.
 relative: en relación a su posición original.
 absolute: se posiciona en relación al contenedor padre.
 fixed: lo dejará fijo y no se moverá.
 sticky: al inicio será relativo su posicionamiento, pero al mover la página se cambiará a fixed.

**Unidades de medida**

Las unidades de medida son aquellas que harán grandes o pequeños nuestros elementos
y dependiendo de cuáles utilicemos, se adaptarán a diferentes pantallas.

* **Unidades absolutas:** son medidas que no cambian, tampoco dependerán de ningún otro factor
estas son:
  - in(pulgadas)
  - cm(centimetros)
  - pc(picas)
  - mm(milímetros)
  - pt(puntos)
  - px(pixeles)
  - Q(cuartos de mm)

* **Unidades relativas: **
Las unidades relativas son aquellas que se acomodan al tamaño de la resolución
de la pantalla y demás factores.
estas son:

- em(M) -> Tamaño de la fuente del navegador
- ex(X) -> Tamaño de la mitad de la fuente del navegador
- ch(zero width) ->ancho del cero
- rem(root M) -> tamaño de fuente raíz
- %(porcentaje) -> relativo a herencia(de acuerdo al contenedor)

* **Selectores**
- Tag: Los elementos de etiqueta seleccionará aquellos que coincidan 
- id
- clase
- relacion(espacio, +, >, ~)

* **PseudoSelectores**
- PseudoClases
- Pseudo elementos
(4 ejemplos)


* **Cascada**
-niveles de cascada


* **Especificidad**
-¿cómo se calcula?
