

=== Resumen Unidad 1
==== 17100244 - Jorge Eduardo Madrigal García

Dentro de la primera unidad se habló de:


**Modelo de Caja - (Box Model)**

 El BoxModel son propiedades que definen el espaciado
 dentro de un elemento, el cuál se encuentra dentro de
 una página web, los cuáles terminan siendo cajas rectangulares.

 Las propiedades utilizadas dentro del Box-Model son:

 * **Content-Box:** Cuando es declarada esta propiedad, el tamaño del
   contenido se puede definir con las propiedades de width,
   min-width, max-width, height, min-height y max-height.
 * **Width:** Ancho de la caja.
 * **Height:** Altura de la caja
 * **Padding:** Relleno que hay entre el contenido y el bloque.
 * **Border:** Grosor y estilo del borde que rodea el contenido(Dentro de la caja).
 * **Margin:** Espacio del borde interior y exterior del elemento.
 * **Outline:** La propiedad Outline sirve para agregar un borde extra y así
    brindar una mejor visualización del elemento.

**Propiedad Display**

 Las cajas que se generan con cada elemento dentro del html
 pueden o no mostrarse de cierta forma, es decir, podemos modificar como se
 mostrará el elemento con esta propiedad, los elementos utilizados en ella son:

 * block: Aquí mostrará el elemento dentro del flujo del documento.
 * inline: Con este elemento, se hará que las cajas estén en la misma línea con
 respecto a otros con la misma propiedad.
 * inline-box: Este elemento hará que la caja se mantenga en el flujo del
 documento y si cuenta con texto hará que lo rodeen.
 * none: Es utilizada habitualmente para esconder un elemento, sin embargo que
 este siga ocupando el espacio donde se encuentra.

**Box Sizing**

 La propiedad de box-sizing dentro de un elemento, nos dará la opción para
 incluir paddings y borders en un elemento con altura y anchura total, además de
 mostrar correctamente en el tamaño de los elementos especificados dentro de
 nuestro html.

 * **content-box: ** es la propiedad por defecto que tienen box-sizing, sin embargo los
 bordes se añadirán a el ancho final desplegado.

 * **border-box: ** con este elemento le diremos al navegador que los valores que
 se especifican se tomen en cuenta para dimensionar los objetos.

**Flujo de documento**

 El flujo es lo que indica como están colocando los componentes de la página,
 basándose en cómo aparecen en el HTML.
 Por ejemplo; la etiqueta que aparezca primero será la que se mostrará también
 en la página como primer lugar.

 sin embargo hay excepciones si se utilizan propiedades de posición, ya que con ellos
 se puede intervenir con el flujo del documento y mostrarse en una posición diferente.

**Tipos de posicionamiento**

El posicionamiento, sirve para cambiar el flujo del documento, ya que con estos se puede o
 no reservar el espacio del elemento.

 static: será estático en como se especifica.
 relative: en relación a su posición original.
 absolute: se posiciona en relación al contenedor padre.
 fixed: lo dejará fijo y no se moverá.
 sticky: al inicio será relativo su posicionamiento, pero al mover la página se cambiará a fixed.

**Unidades de medida**

Las unidades de medida son aquellas que harán grandes o pequeños nuestros elementos
y dependiendo de cuáles utilicemos, se adaptarán a diferentes pantallas.

* **Unidades absolutas:** son medidas que no cambian, tampoco dependerán de ningún otro factor
estas son:
  - in(pulgadas)
  - cm(centimetros)
  - pc(picas)
  - mm(milímetros)
  - pt(puntos)
  - px(pixeles)
  - Q(cuartos de mm)

* **Unidades relativas: **
Las unidades relativas son aquellas que se acomodan al tamaño de la resolución
de la pantalla y demás factores.
estas son:

- em(M) -> Tamaño de la fuente del navegador
- ex(X) -> Tamaño de la mitad de la fuente del navegador
- ch(zero width) ->ancho del cero
- rem(root M) -> tamaño de fuente raíz
- %(porcentaje) -> relativo a herencia(de acuerdo al contenedor)

* **Selectores**
- Tag: Los elementos de etiqueta seleccionará aquellos que coincidan con el
nombre. por ejemplo -> p{ } tomará todos los elementos párrafo que estén dentro
de nuestro documento.
- id: Con esto, se indica a un solo elemento las propiedades, ya que sólo existirá
un solo id dentro de nuestro html.
- clase: Los elementos que tengan la clase especificada solamente serán aquellos
que tengan especificada tal clase.
- relacion(espacio, +, >, ~): Estos nos sirven para separar e indicar aquellos
elementos que necesitemos, mediante el css.

 espacio: indicará los elementos que desciendan de el que está a la izquierda.
 +: Aquellos elementos que sean hermanos de el elemento que está a la izquierda del signo.
 -:
 >: Aquellos elementos que sean primeros hijos de un contenedor padre.
 ~:  Inidicará todas las etiquetas siguientes.

* **PseudoSelectores**

 Los pseudo selectores de atributos, son aquellos selectores que no son un selector.
 son divididos en dos:

  1. Pseudo Elementos y 2. Pseudo clases.

- **PseudoClases:**  Son definidas por le navegador y son palabras clave que se
especifica como un estado especial sobre un elemento seleccionado. ejemplos:

 :hover aplicará un estilo cuando el usuario ponga su mouse sobre el elemento especificado
por el selector.

 :active represent un elemento que el usuario activa, como botones, sin embargo será
 ignorado si hay otras pseudoclases posteriores, esto se rige por el orden LVHA(Link, Visited, Hover, Active).

 :disabled indica que cualquier elemento con esta pseudoclase será ignorado. puede aplicarse
 para pasar del estado activo a desactivado.

 :fullscreen será un elemento que se muestra cuando el navegador está única y exclusivamente en modo de pantalla completa.

 :checked se utilizará para cualquier radio input, checkbox u option, y funcionará para marcar un elemento que esté activado.

- **Pseudo elementos:**

 ::first-letter tomará la primera letra del texto donde se utilice.

 ::first-line tomará la primera línea del texto donde se utilice.

 ::before será aquello que hará el elemento "antes" de.

 ::after será aquello que hará el elemento "después" de.


* **Cascada**

 El modelo de cascada, es la forma o reglas que indicarán cuál propiedad se mostrará
 al ponerla dentro de nuestro código.

 Este modelo de cascada indica que, siempre prevalecerá la última regla definida, la cuál mezclará y sobreescribirá
 cualquier anterior.

Por ejemplo:

[source,css]
div {
  color: red;
  padding: 8px;
 }
div {
  color: blue;
  background-color:grey;
 }

Lo que hará en lo anterior será una unión de ambos, tomando como principal la última propiedad definida.
ignorando así el color rojo y poniendo el color azul, con las demás propiedades activas.

 esto va de la mano con la importancia, ya que existen varios tipos de hojas de estilos, los cuáles tomará el navegador dependiendo
 de su valor.

importancia
|===
|Importancia| tipo de hoja| descripción
|3
|Navegador
|son aquellos estilos que aplica el navegador por defecto.
|2
|Estilos de usuario
|son las hojas de estilos que el usuario agrega.
|1
|CSS de autor
|son los estilos que indica dentro de la página el autor del sitio web.
|===

Existe también una excepción a esto, se trata de una regla llamada **!important**. Esta regla lo que hará es ignorar
cualquier otra parecida y se aplicará ella, pero si una propiedad con !important está declarada en el nivel 2 y nivel 1, tomará como prioridad
aquella del nivel 2.


* **Especificidad**
 La especificidad es la importancia que tenga una declaración css. Cuando hay varios elementos
 con la misma especificidad, se tomará el último declarado en el css.

 El orden de importancia es el siguiente de menor a mayor especificidad(peso/importancia)
 - selectores de título y pseudo-Elementos
 - selectores de clase, atributos y pseudo-clases
 - selectores de ID.


|===
|1000|100|10|1
|===

* elementos o pseudo elemento: valor 1
* clases, pseudo-clases o atributos: valor 10
* id: valor 100
* elementos declarados desde style en el html: valor 1000

Con esto, podremos hacer una suma o determinar cuál propiedad se aplicará
en nuestro código. Entonces, su valor de importancia se determinará por la suma de cada elemento; por eso se ordenan de mayor a menor, para
poder calcularlo mejor.


Por ejemplo:
[source,css]
#nav .selected a:hover{
color: blue;
}

El código anterior tendrá un peso de:
|===
|0|1|2|1
|===

121 tal y como se muestra en la tabla, ya que presenta una clase + pseudoclase
(.selected :hover = 10+10 -> 20), un id(#nav = 100) y un elemento(a = 1)

sin embargo, como se explicó en el bloque anterior, si se agrega una regla **!important** a nuestro código, el navegador tomará
como preferencia tal grupo de elementos por encima de los demás.
